version: '3.8'

services:
  db:
    image: mysql:8.0
    # Use platform if you encounter issues, usually fine on modern Docker for Mac
    # platform: linux/amd64 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  php:
    build: ./.docker/php
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    restart: always
    environment:
      # Allow sending emails via msmtp or just for logging
      msmtp_host: mailhog
      msmtp_port: 1025

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always

volumes:
  db_data:
